# Generated by Django 4.2.1 on 2023-05-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_stations', '0002_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_stations.fueltype')),
                ('id_GasStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_stations.gasstation')),
            ],
        ),
    ]
