# Generated by Django 4.2.1 on 2023-05-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_stations', '0005_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_stations.fueltype')),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_stations.gasstation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_stations.profile')),
            ],
        ),
    ]
